Updated Cuckoo version from 0.12.1 to 1.0.6

diff --git a/Pods/Cuckoo/run b/Pods/Cuckoo/run
--- a/Pods/Cuckoo/run
+++ b/Pods/Cuckoo/run
@@ -1,20 +1,24 @@
 #!/usr/bin/env bash
 
-SCRIPT_PATH="$(dirname "$0")"
+SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd)"
 FILE_NAME="cuckoo_generator"
 FILE_PATH="$SCRIPT_PATH/$FILE_NAME"
 GREP_OPTIONS=""
 
 function perform_curl {
   if [[ ! -z "$GITHUB_ACCESS_TOKEN" ]]; then
-    REQUEST_HEADER="-H 'Authorization: token ${GITHUB_ACCESS_TOKEN}'"
-    echo "$REQUEST_HEADER"
+    CURL_OPTIONS=(-H "Authorization: token $GITHUB_ACCESS_TOKEN")
   fi
-  echo "$1"
 
-  DOWNLOAD_URL=$(curl "$REQUEST_HEADER" "$1" | grep -oe '"browser_download_url":\s*"[^" ]*"' | grep -oe 'http[^" ]*' | grep "$FILE_NAME" | head -1)
-  echo "$DOWNLOAD_URL"
-  curl "$REQUEST_HEADER" -Lo "$FILE_NAME" "$DOWNLOAD_URL"
+  DOWNLOAD_URL=$(curl "${CURL_OPTIONS[@]}" "$1" | grep -oe '"browser_download_url":\s*"[^" ]*"' | grep -oe 'http[^" ]*' | grep "$FILE_NAME" | head -1)
+  
+  if [[ -z "$DOWNLOAD_URL" ]]; then
+    echo "Error: Failed to fetch download URL for the Cuckoo Generator."
+    exit 1
+  else
+    echo "Downloading Cuckoo Generator from URL: $DOWNLOAD_URL"
+    curl "${CURL_OPTIONS[@]}" -Lo "$FILE_PATH" "$DOWNLOAD_URL"
+  fi
 }
 
 function download_generator {
@@ -42,12 +46,14 @@ function build_generator {
       fi
       mv "$SCRIPT_PATH/Generator/.build/release/$FILE_NAME" "$FILE_PATH"
     else
-      echo "Couldn't build. Generator source code not found. (expected in the `Generator` directory)"
+      echo "Couldn't build. Generator source code not found. (expected in the 'Generator' directory)"
       download_generator "$2"
     fi
   fi
   popd
 }
+
+echo "Script path: $SCRIPT_PATH"
 
 # parse arguments
 POSITIONAL=()
@@ -55,21 +61,23 @@ while [[ $# -gt 0 ]]
 do
 case $1 in
   -d|--download)
-    if [[ "$2" = --* ]]; then
+    if [[ "$2" = "latest" ]]; then
       DOWNLOAD="latest"
+      shift
     else
       DOWNLOAD=$(echo "$2" | grep -e "\d\d*\.\d\d*\.\d\d*")
-      if [[ -z $DOWNLOAD ]]; then
-        echo "Invalid Cuckoo Generator version: $2; Please use the semantic versioning. (e.g. 0.12.0)"
-        exit 1
+      if [[ ! -z $DOWNLOAD ]]; then
+        shift
+      else
+        DOWNLOAD="latest"
       fi
-      shift
     fi
     shift
   ;;
   
   -c|--clean)
     CLEAN=1
+    echo "Performing clean build."
     shift
   ;;
   
